/**
 * Interface for tool configuration
 */
export interface Tool {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: string;
  category: string;
  status: "active" | "inactive" | "beta";
  tags: string[];
  featured?: boolean;
  popular?: boolean;
}

/**
 * Interface for tool category configuration
 */
export interface ToolCategory {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  href: string;
}

/**
 * Array of tool categories
 */
export const toolCategories: ToolCategory[] = [
  {
    id: "developer",
    name: "Developer Tools",
    description: "Code formatters, generators, and validators",
    icon: "Code",
    color: "bg-green-500",
    href: "/tools/developer",
  },
  {
    id: "general",
    name: "General Utilities",
    description: "Miscellaneous tools for everyday tasks",
    icon: "Wrench",
    color: "bg-indigo-500",
    href: "/tools/general",
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Resize, crop, convert, and enhance images",
    icon: "ImageIcon",
    color: "bg-blue-500",
    href: "/tools/image",
  },
  {
    id: "number",
    name: "Number Tools",
    description: "Calculators, converters, and math utilities",
    icon: "Calculator",
    color: "bg-orange-500",
    href: "/tools/number",
  },
  {
    id: "pdf",
    name: "PDF Utilities",
    description: "Extract, merge, compress, and manipulate PDF files",
    icon: "FileText",
    color: "bg-red-500",
    href: "/tools/pdf",
  },
  {
    id: "text",
    name: "Text Utilities",
    description: "Text processing and transformation tools",
    icon: "Type",
    color: "bg-purple-500",
    href: "/tools/text",
  },
  {
    id: "time",
    name: "Time Utilities",
    description: "Date, time, and timezone tools",
    icon: "Clock",
    color: "bg-teal-500",
    href: "/tools/time",
  },
  {
    id: "units",
    name: "Unit Converters",
    description: "Convert between different units of measurement",
    icon: "Zap",
    color: "bg-pink-500",
    href: "/tools/units",
  },
  {
    id: "web3",
    name: "Web3 & Crypto",
    description: "Blockchain, cryptocurrency, and Web3 tools",
    icon: "Zap",
    color: "bg-yellow-500",
    href: "/tools/web3",
  },
];

/**
 * Array of all tools
 */
export const allTools: Tool[] = [
  // PDF Utilities (16 tools)
  {
    id: "pdf-extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages from PDF documents",
    href: "/tools/pdf/extract-pages",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "extract", "pages"],
    featured: true,
    popular: true,
  },
  {
    id: "pdf-merge",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one",
    href: "/tools/pdf/merge",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "merge", "combine"],
    featured: true,
    popular: true,
  },
  {
    id: "pdf-compress",
    name: "Compress PDF",
    description: "Reduce PDF file size while maintaining quality",
    href: "/tools/pdf/compress",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "compress", "optimize"],
  },
  {
    id: "pdf-encrypt",
    name: "Encrypt PDF",
    description: "Add password protection to PDF files",
    href: "/tools/pdf/encrypt",
    icon: "Lock",
    category: "pdf",
    status: "active",
    tags: ["pdf", "encrypt", "password", "security"],
  },
  {
    id: "pdf-decrypt",
    name: "Decrypt PDF",
    description: "Remove password protection from PDF files",
    href: "/tools/pdf/decrypt",
    icon: "Unlock",
    category: "pdf",
    status: "active",
    tags: ["pdf", "decrypt", "unlock"],
  },
  {
    id: "pdf-rotate",
    name: "Rotate PDF",
    description: "Rotate pages in PDF documents",
    href: "/tools/pdf/rotate",
    icon: "RotateCw",
    category: "pdf",
    status: "active",
    tags: ["pdf", "rotate", "orientation"],
  },
  {
    id: "pdf-reorder",
    name: "Reorder Pages",
    description: "Rearrange pages in PDF documents",
    href: "/tools/pdf/reorder",
    icon: "Shuffle",
    category: "pdf",
    status: "active",
    tags: ["pdf", "reorder", "rearrange"],
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to image files",
    href: "/tools/pdf/to-image",
    icon: "ImageIcon",
    category: "pdf",
    status: "active",
    tags: ["pdf", "convert", "image"],
  },
  {
    id: "pdf-from-image",
    name: "Image to PDF",
    description: "Convert images to PDF documents",
    href: "/tools/pdf/from-image",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "convert", "image"],
  },

  {
    id: "pdf-split",
    name: "Split PDF",
    description: "Split PDF documents into multiple files",
    href: "/tools/pdf/split",
    icon: "Split",
    category: "pdf",
    status: "active",
    tags: ["pdf", "split", "divide"],
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract text content from PDF files",
    href: "/tools/pdf/to-text",
    icon: "Type",
    category: "pdf",
    status: "active",
    tags: ["pdf", "text", "extract"],
  },
  {
    id: "pdf-annotate",
    name: "Annotate PDF",
    description: "Add annotations and comments to PDFs",
    href: "/tools/pdf/annotate",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "annotate", "comments"],
  },
  {
    id: "pdf-form-filler",
    name: "Form Filler",
    description: "Fill out PDF forms programmatically",
    href: "/tools/pdf/form-filler",
    icon: "FileText",
    category: "pdf",
    status: "active",
    tags: ["pdf", "forms", "fill"],
  },
  {
    id: "pdf-bookmarks",
    name: "Bookmark Creator",
    description: "Add bookmarks and navigation to PDFs",
    href: "/tools/pdf/bookmarks",
    icon: "Bookmark",
    category: "pdf",
    status: "active",
    tags: ["pdf", "bookmarks", "navigation"],
  },
  {
    id: "pdf-remove-password",
    name: "Remove Password",
    description: "Remove password protection from PDFs",
    href: "/tools/pdf/remove-password",
    icon: "ShieldX",
    category: "pdf",
    status: "active",
    tags: ["pdf", "password", "remove"],
  },

  // Image Tools (15 tools)
  {
    id: "image-resize",
    name: "Resize Image",
    description: "Resize images while maintaining aspect ratio",
    href: "/tools/image/resize",
    icon: "ImageIcon",
    category: "image",
    status: "active",
    tags: ["image", "resize", "scale"],
    featured: true,
    popular: true,
  },
  {
    id: "image-crop",
    name: "Crop Image",
    description: "Crop images to specific dimensions or aspect ratios",
    href: "/tools/image/crop",
    icon: "Crop",
    category: "image",
    status: "active",
    tags: ["image", "crop", "trim"],
  },
  {
    id: "image-convert",
    name: "Convert Format",
    description: "Convert between different image formats",
    href: "/tools/image/convert",
    icon: "RefreshCw",
    category: "image",
    status: "active",
    tags: ["image", "convert", "format"],
  },
  {
    id: "image-compress",
    name: "Compress Image",
    description: "Reduce image file size while maintaining quality",
    href: "/tools/image/compress",
    icon: "Zap",
    category: "image",
    status: "active",
    tags: ["image", "compress", "optimize"],
  },
  {
    id: "image-metadata",
    name: "Metadata Viewer",
    description: "View and extract EXIF data from images",
    href: "/tools/image/metadata",
    icon: "Eye",
    category: "image",
    status: "active",
    tags: ["image", "metadata", "exif"],
  },
  {
    id: "image-watermark",
    name: "Add Watermark",
    description: "Add text or image watermarks to photos",
    href: "/tools/image/watermark",
    icon: "Droplets",
    category: "image",
    status: "active",
    tags: ["image", "watermark", "text"],
  },
  {
    id: "image-palette",
    name: "Color Palette",
    description: "Extract color palettes from images",
    href: "/tools/image/palette",
    icon: "Palette",
    category: "image",
    status: "active",
    tags: ["image", "color", "palette"],
  },
  {
    id: "image-thumbnail",
    name: "Create Thumbnail",
    description: "Generate thumbnails from images",
    href: "/tools/image/thumbnail",
    icon: "ImageIcon",
    category: "image",
    status: "active",
    tags: ["image", "thumbnail", "preview"],
  },
  {
    id: "image-exif-cleaner",
    name: "EXIF Cleaner",
    description: "Remove metadata and EXIF data from images",
    href: "/tools/image/exif-cleaner",
    icon: "Eraser",
    category: "image",
    status: "active",
    tags: ["image", "exif", "privacy"],
  },

  {
    id: "image-brightness",
    name: "Brightness/Contrast",
    description: "Adjust image brightness and contrast",
    href: "/tools/image/brightness",
    icon: "Sun",
    category: "image",
    status: "active",
    tags: ["image", "brightness", "contrast"],
  },
  {
    id: "image-grayscale",
    name: "Grayscale",
    description: "Convert images to grayscale",
    href: "/tools/image/grayscale",
    icon: "Contrast",
    category: "image",
    status: "active",
    tags: ["image", "grayscale", "black-white"],
  },
  {
    id: "image-blur",
    name: "Blur Tool",
    description: "Apply blur effects to images",
    href: "/tools/image/blur",
    icon: "CloudyIcon",
    category: "image",
    status: "active",
    tags: ["image", "blur", "effect"],
  },
  {
    id: "image-rotate",
    name: "Rotation Tool",
    description: "Rotate images by any angle",
    href: "/tools/image/rotate",
    icon: "RotateCw",
    category: "image",
    status: "active",
    tags: ["image", "rotate", "angle"],
  },
  {
    id: "image-flip",
    name: "Flip Tool",
    description: "Flip images horizontally or vertically",
    href: "/tools/image/flip",
    icon: "FlipHorizontal",
    category: "image",
    status: "active",
    tags: ["image", "flip", "mirror"],
  },

  // Developer Tools (25 tools)
  {
    id: "dev-json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    href: "/tools/developer/json-formatter",
    icon: "Code",
    category: "developer",
    status: "active",
    tags: ["json", "format", "validate"],
    featured: true,
    popular: true,
  },
  {
    id: "dev-regex",
    name: "Regex Tester",
    description: "Test and debug regular expressions",
    href: "/tools/developer/regex",
    icon: "Search",
    category: "developer",
    status: "active",
    tags: ["regex", "test", "pattern"],
    popular: true,
  },
  {
    id: "dev-jwt",
    name: "JWT Debugger",
    description: "Decode and verify JSON Web Tokens",
    href: "/tools/developer/jwt",
    icon: "Key",
    category: "developer",
    status: "active",
    tags: ["jwt", "token", "decode"],
  },
  {
    id: "dev-base64",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 data",
    href: "/tools/developer/base64",
    icon: "Hash",
    category: "developer",
    status: "active",
    tags: ["base64", "encode", "decode"],
    featured: true,
  },
  {
    id: "dev-uuid",
    name: "UUID Generator",
    description: "Generate universally unique identifiers",
    href: "/tools/developer/uuid",
    icon: "Zap",
    category: "developer",
    status: "active",
    tags: ["uuid", "generate", "unique"],
  },
  {
    id: "dev-checksum",
    name: "Checksum Generator",
    description: "Generate MD5, SHA1, SHA256 checksums",
    href: "/tools/developer/checksum",
    icon: "CheckSquare",
    category: "developer",
    status: "active",
    tags: ["checksum", "hash", "md5", "sha"],
  },
  {
    id: "dev-cron-generator",
    name: "Cron Generator",
    description: "Generate cron expressions with visual interface",
    href: "/tools/developer/cron-generator",
    icon: "Calendar",
    category: "developer",
    status: "active",
    tags: ["cron", "schedule", "generate"],
  },
  {
    id: "dev-cron-decoder",
    name: "Cron Decoder",
    description: "Decode and explain cron expressions",
    href: "/tools/developer/cron-decoder",
    icon: "Calendar",
    category: "developer",
    status: "active",
    tags: ["cron", "decode", "explain"],
  },
  {
    id: "dev-sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    href: "/tools/developer/sql-formatter",
    icon: "Database",
    category: "developer",
    status: "active",
    tags: ["sql", "format", "query"],
  },
  {
    id: "dev-js-minifier",
    name: "JS/TS Minifier",
    description: "Minify JavaScript and TypeScript code",
    href: "/tools/developer/js-minifier",
    icon: "Minimize",
    category: "developer",
    status: "active",
    tags: ["javascript", "typescript", "minify"],
  },
  {
    id: "dev-flexbox",
    name: "CSS Flexbox",
    description: "Visual CSS Flexbox generator",
    href: "/tools/developer/flexbox",
    icon: "Layout",
    category: "developer",
    status: "active",
    tags: ["css", "flexbox", "layout"],
  },
  {
    id: "dev-mock-data",
    name: "Mock Data",
    description: "Generate mock data for testing",
    href: "/tools/developer/mock-data",
    icon: "Shuffle",
    category: "developer",
    status: "active",
    tags: ["mock", "data", "testing"],
  },
  {
    id: "dev-html-minifier",
    name: "HTML/CSS Minifier",
    description: "Minify HTML and CSS code",
    href: "/tools/developer/html-minifier",
    icon: "Minimize",
    category: "developer",
    status: "active",
    tags: ["html", "css", "minify"],
  },
  {
    id: "dev-url-parser",
    name: "URL Parser",
    description: "Parse and analyze URLs",
    href: "/tools/developer/url-parser",
    icon: "Globe",
    category: "developer",
    status: "active",
    tags: ["url", "parse", "analyze"],
  },
  {
    id: "dev-color-converter",
    name: "Color Converter",
    description: "Convert between color formats",
    href: "/tools/developer/color-converter",
    icon: "Palette",
    category: "developer",
    status: "active",
    tags: ["color", "convert", "hex", "rgb"],
  },
  {
    id: "dev-api-mock",
    name: "API Mock",
    description: "Create mock API responses",
    href: "/tools/developer/api-mock",
    icon: "Server",
    category: "developer",
    status: "active",
    tags: ["api", "mock", "response"],
  },
  {
    id: "dev-code-diff",
    name: "Code Diff",
    description: "Compare code differences",
    href: "/tools/developer/code-diff",
    icon: "GitCompare",
    category: "developer",
    status: "active",
    tags: ["code", "diff", "compare"],
  },
  {
    id: "dev-yaml",
    name: "YAML Formatter",
    description: "Format and validate YAML files",
    href: "/tools/developer/yaml",
    icon: "FileText",
    category: "developer",
    status: "active",
    tags: ["yaml", "format", "validate"],
  },
  {
    id: "dev-graphql",
    name: "GraphQL Formatter",
    description: "Format GraphQL queries and schemas",
    href: "/tools/developer/graphql",
    icon: "Layers",
    category: "developer",
    status: "active",
    tags: ["graphql", "format", "query"],
  },
  {
    id: "dev-html-entity",
    name: "HTML Entity",
    description: "Encode and decode HTML entities",
    href: "/tools/developer/html-entity",
    icon: "Globe",
    category: "developer",
    status: "active",
    tags: ["html", "entity", "encode"],
  },
  {
    id: "dev-xml-formatter",
    name: "XML Formatter",
    description: "Format and validate XML documents",
    href: "/tools/developer/xml-formatter",
    icon: "FileText",
    category: "developer",
    status: "active",
    tags: ["xml", "format", "validate"],
  },
  {
    id: "dev-css-minifier",
    name: "CSS Minifier",
    description: "Minify CSS stylesheets",
    href: "/tools/developer/css-minifier",
    icon: "Minimize",
    category: "developer",
    status: "active",
    tags: ["css", "minify", "compress"],
  },
  {
    id: "dev-markdown-preview",
    name: "Markdown Preview",
    description: "Preview Markdown with live rendering",
    href: "/tools/developer/markdown-preview",
    icon: "FileText",
    category: "developer",
    status: "active",
    tags: ["markdown", "preview", "render"],
  },
  {
    id: "dev-json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON data to CSV format",
    href: "/tools/developer/json-to-csv",
    icon: "FileText",
    category: "developer",
    status: "active",
    tags: ["json", "csv", "convert"],
  },

  // Text Utilities (20 tools)
  {
    id: "text-case-converter",
    name: "Case Converter",
    description: "Convert text between different cases",
    href: "/tools/text/case-converter",
    icon: "Type",
    category: "text",
    status: "active",
    tags: ["text", "case", "convert"],
    popular: true,
  },
  {
    id: "text-word-counter",
    name: "Word Counter",
    description: "Count words, characters, and paragraphs",
    href: "/tools/text/word-counter",
    icon: "Hash",
    category: "text",
    status: "active",
    tags: ["text", "count", "words"],
    featured: true,
  },
  {
    id: "text-find-replace",
    name: "Find & Replace",
    description: "Search and replace text with advanced options",
    href: "/tools/text/find-replace",
    icon: "Search",
    category: "text",
    status: "active",
    tags: ["text", "find", "replace"],
  },
  {
    id: "text-lorem",
    name: "Lorem Generator",
    description: "Generate Lorem Ipsum placeholder text",
    href: "/tools/text/lorem",
    icon: "FileText",
    category: "text",
    status: "active",
    tags: ["lorem", "ipsum", "placeholder"],
  },
  {
    id: "text-split",
    name: "Text Splitter",
    description: "Split text by delimiters or patterns",
    href: "/tools/text/split",
    icon: "Split",
    category: "text",
    status: "inactive",
    tags: ["text", "split", "delimiter"],
  },
  {
    id: "text-reverse",
    name: "Reverse Text",
    description: "Reverse text character by character",
    href: "/tools/text/reverse",
    icon: "RotateCcw",
    category: "text",
    status: "inactive",
    tags: ["text", "reverse", "flip"],
  },
  {
    id: "text-trim",
    name: "Trim Text",
    description: "Remove whitespace and clean text",
    href: "/tools/text/trim",
    icon: "Scissors",
    category: "text",
    status: "inactive",
    tags: ["text", "trim", "whitespace"],
  },
  {
    id: "text-remove-duplicates",
    name: "Remove Duplicates",
    description: "Remove duplicate lines from text",
    href: "/tools/text/remove-duplicates",
    icon: "Copy",
    category: "text",
    status: "inactive",
    tags: ["text", "duplicate", "unique"],
  },
  {
    id: "text-sort",
    name: "Sort Words",
    description: "Sort text lines alphabetically",
    href: "/tools/text/sort",
    icon: "ArrowUpDown",
    category: "text",
    status: "inactive",
    tags: ["text", "sort", "alphabetical"],
  },
  {
    id: "text-extract-html",
    name: "Extract from HTML",
    description: "Extract text content from HTML",
    href: "/tools/text/extract-html",
    icon: "Code",
    category: "text",
    status: "inactive",
    tags: ["text", "html", "extract"],
  },
  {
    id: "text-url-encode",
    name: "URL Encoding",
    description: "Encode text for URL usage",
    href: "/tools/text/url-encode",
    icon: "Zap",
    category: "text",
    status: "inactive",
    tags: ["text", "url", "encode"],
  },
  {
    id: "text-url-decode",
    name: "URL Decoding",
    description: "Decode URL-encoded text",
    href: "/tools/text/url-decode",
    icon: "Zap",
    category: "text",
    status: "inactive",
    tags: ["text", "url", "decode"],
  },
  {
    id: "text-regex-generator",
    name: "Regex Generator",
    description: "Generate regular expressions from text",
    href: "/tools/text/regex-generator",
    icon: "Zap",
    category: "text",
    status: "inactive",
    tags: ["text", "regex", "generate"],
  },
  {
    id: "text-morse",
    name: "Morse Code",
    description: "Convert text to/from Morse code",
    href: "/tools/text/morse",
    icon: "Zap",
    category: "text",
    status: "inactive",
    tags: ["text", "morse", "code"],
  },
  {
    id: "text-binary",
    name: "Binary Converter",
    description: "Convert text to/from binary",
    href: "/tools/text/binary",
    icon: "Binary",
    category: "text",
    status: "inactive",
    tags: ["text", "binary", "convert"],
  },
  {
    id: "text-frequency",
    name: "Word Frequency",
    description: "Analyze word frequency in text",
    href: "/tools/text/frequency",
    icon: "BarChart",
    category: "text",
    status: "inactive",
    tags: ["text", "frequency", "analyze"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare differences between texts",
    href: "/tools/text/diff",
    icon: "GitCompare",
    category: "text",
    status: "inactive",
    tags: ["text", "diff", "compare"],
  },

  {
    id: "text-remove-breaks",
    name: "Remove Line Breaks",
    description: "Remove or normalize line breaks",
    href: "/tools/text/remove-breaks",
    icon: "Minus",
    category: "text",
    status: "inactive",
    tags: ["text", "line", "breaks"],
  },
  {
    id: "text-indent",
    name: "Indent Text",
    description: "Add or remove text indentation",
    href: "/tools/text/indent",
    icon: "Indent",
    category: "text",
    status: "inactive",
    tags: ["text", "indent", "format"],
  },

  // Number Tools (18 tools)
  {
    id: "number-base-converter",
    name: "Base Converter",
    description: "Convert numbers between different bases",
    href: "/tools/number/base-converter",
    icon: "Hash",
    category: "number",
    status: "active",
    tags: ["number", "base", "convert"],
  },
  {
    id: "number-formatter",
    name: "Number Formatter",
    description: "Format numbers with separators and locales",
    href: "/tools/number/formatter",
    icon: "Calculator",
    category: "number",
    status: "inactive",
    tags: ["number", "format", "locale"],
  },
  {
    id: "number-random",
    name: "Random Generator",
    description: "Generate random numbers with constraints",
    href: "/tools/number/random",
    icon: "Shuffle",
    category: "number",
    status: "inactive",
    tags: ["number", "random", "generate"],
  },
  {
    id: "number-prime",
    name: "Prime Checker",
    description: "Check if numbers are prime",
    href: "/tools/number/prime",
    icon: "CheckCircle",
    category: "number",
    status: "inactive",
    tags: ["number", "prime", "check"],
  },
  {
    id: "number-percentage",
    name: "Percentage Calc",
    description: "Calculate percentages and ratios",
    href: "/tools/number/percentage",
    icon: "Percent",
    category: "number",
    status: "inactive",
    tags: ["number", "percentage", "ratio"],
  },
  {
    id: "number-ratio",
    name: "Ratio Simplifier",
    description: "Simplify mathematical ratios",
    href: "/tools/number/ratio",
    icon: "Divide",
    category: "number",
    status: "inactive",
    tags: ["number", "ratio", "simplify"],
  },
  {
    id: "number-sequence",
    name: "Sequence Generator",
    description: "Generate number sequences",
    href: "/tools/number/sequence",
    icon: "List",
    category: "number",
    status: "inactive",
    tags: ["number", "sequence", "generate"],
  },
  {
    id: "number-rounding",
    name: "Rounding Tool",
    description: "Round numbers to specified precision",
    href: "/tools/number/rounding",
    icon: "RotateCcw",
    category: "number",
    status: "inactive",
    tags: ["number", "round", "precision"],
  },
  {
    id: "number-factorization",
    name: "Factorization",
    description: "Find prime factors of numbers",
    href: "/tools/number/factorization",
    icon: "Zap",
    category: "number",
    status: "inactive",
    tags: ["number", "factor", "prime"],
  },
  {
    id: "number-roman",
    name: "Roman Numerals",
    description: "Convert to/from Roman numerals",
    href: "/tools/number/roman",
    icon: "Crown",
    category: "number",
    status: "inactive",
    tags: ["number", "roman", "numeral"],
  },
  {
    id: "number-matrix",
    name: "Matrix Calculator",
    description: "Perform matrix operations",
    href: "/tools/number/matrix",
    icon: "Grid",
    category: "number",
    status: "inactive",
    tags: ["number", "matrix", "calculate"],
  },
  {
    id: "number-scientific",
    name: "Scientific Notation",
    description: "Convert to scientific notation",
    href: "/tools/number/scientific",
    icon: "Microscope",
    category: "number",
    status: "inactive",
    tags: ["number", "scientific", "notation"],
  },
  {
    id: "number-significant",
    name: "Significant Figures",
    description: "Round to significant figures",
    href: "/tools/number/significant",
    icon: "Target",
    category: "number",
    status: "inactive",
    tags: ["number", "significant", "figures"],
  },
  {
    id: "number-gcd-lcm",
    name: "GCD/LCM",
    description: "Find greatest common divisor and least common multiple",
    href: "/tools/number/gcd-lcm",
    icon: "GitBranch",
    category: "number",
    status: "inactive",
    tags: ["number", "gcd", "lcm"],
  },
  {
    id: "number-factorial",
    name: "Factorial",
    description: "Calculate factorials and combinations",
    href: "/tools/number/factorial",
    icon: "RatioIcon",
    category: "number",
    status: "inactive",
    tags: ["number", "factorial", "combination"],
  },
  {
    id: "number-quadratic",
    name: "Quadratic Solver",
    description: "Solve quadratic equations",
    href: "/tools/number/quadratic",
    icon: "TrendingUp",
    category: "number",
    status: "inactive",
    tags: ["number", "quadratic", "equation"],
  },
  {
    id: "number-to-words",
    name: "Number to Words",
    description: "Convert numbers to written words",
    href: "/tools/number/to-words",
    icon: "Type",
    category: "number",
    status: "inactive",
    tags: ["number", "words", "convert"],
  },
  {
    id: "number-shuffle",
    name: "Sequence Shuffler",
    description: "Shuffle and randomize number sequences",
    href: "/tools/number/shuffle",
    icon: "ArrowUpDown",
    category: "number",
    status: "inactive",
    tags: ["number", "shuffle", "randomize"],
  },

  // Time Utilities (15 tools)
  {
    id: "time-timezone",
    name: "Timezone Converter",
    description: "Convert time between different timezones",
    href: "/tools/time/timezone",
    icon: "Globe",
    category: "time",
    status: "active",
    tags: ["time", "timezone", "convert"],
    featured: true,
  },
  {
    id: "time-stopwatch",
    name: "Stopwatch",
    description: "Precise stopwatch with lap timing",
    href: "/tools/time/stopwatch",
    icon: "TimerIcon",
    category: "time",
    status: "active",
    tags: ["time", "stopwatch", "timer"],
  },
  {
    id: "time-duration",
    name: "Duration Calculator",
    description: "Calculate time differences and durations",
    href: "/tools/time/duration",
    icon: "Clock",
    category: "time",
    status: "inactive",
    tags: ["time", "duration", "calculate"],
  },
  {
    id: "time-countdown",
    name: "Countdown Timer",
    description: "Create countdown timers for events",
    href: "/tools/time/countdown",
    icon: "Timer",
    category: "time",
    status: "inactive",
    tags: ["time", "countdown", "timer"],
  },
  {
    id: "time-timestamp",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to readable dates",
    href: "/tools/time/timestamp",
    icon: "Hash",
    category: "time",
    status: "inactive",
    tags: ["time", "timestamp", "unix"],
  },
  {
    id: "time-format",
    name: "Time Format",
    description: "Format time in different formats",
    href: "/tools/time/format",
    icon: "Type",
    category: "time",
    status: "inactive",
    tags: ["time", "format", "display"],
  },
  {
    id: "time-age",
    name: "Age Calculator",
    description: "Calculate age and time since birth",
    href: "/tools/time/age",
    icon: "User",
    category: "time",
    status: "inactive",
    tags: ["time", "age", "calculate"],
  },
  {
    id: "time-iso8601",
    name: "ISO 8601 Formatter",
    description: "Format dates in ISO 8601 standard",
    href: "/tools/time/iso8601",
    icon: "FileText",
    category: "time",
    status: "inactive",
    tags: ["time", "iso", "format"],
  },
  {
    id: "time-calendar",
    name: "Calendar Calculator",
    description: "Calculate dates and calendar operations",
    href: "/tools/time/calendar",
    icon: "Calendar",
    category: "time",
    status: "inactive",
    tags: ["time", "calendar", "date"],
  },
  {
    id: "time-unit-converter",
    name: "Time Unit Converter",
    description: "Convert between time units",
    href: "/tools/time/unit-converter",
    icon: "ArrowLeftRight",
    category: "time",
    status: "inactive",
    tags: ["time", "unit", "convert"],
  },
  {
    id: "time-business-days",
    name: "Business Days",
    description: "Calculate business days between dates",
    href: "/tools/time/business-days",
    icon: "Briefcase",
    category: "time",
    status: "inactive",
    tags: ["time", "business", "days"],
  },
  {
    id: "time-leap-year",
    name: "Leap Year Checker",
    description: "Check if years are leap years",
    href: "/tools/time/leap-year",
    icon: "CheckCircle",
    category: "time",
    status: "inactive",
    tags: ["time", "leap", "year"],
  },
  {
    id: "time-world-clock",
    name: "World Clock",
    description: "Display time in multiple timezones",
    href: "/tools/time/world-clock",
    icon: "Globe",
    category: "time",
    status: "inactive",
    tags: ["time", "world", "clock"],
  },
  {
    id: "time-date-formatter",
    name: "Date Formatter",
    description: "Format dates in various formats",
    href: "/tools/time/date-formatter",
    icon: "CalendarDays",
    category: "time",
    status: "inactive",
    tags: ["time", "date", "format"],
  },
  {
    id: "time-timezone-offset",
    name: "Timezone Offset",
    description: "Calculate timezone offsets",
    href: "/tools/time/timezone-offset",
    icon: "MapPin",
    category: "time",
    status: "inactive",
    tags: ["time", "timezone", "offset"],
  },

  // Unit Converters (15 tools)
  {
    id: "units-length",
    name: "Length Converter",
    description: "Convert between meters, feet, inches, and more",
    href: "/tools/units/length",
    icon: "Ruler",
    category: "units",
    status: "inactive",
    tags: ["units", "length", "convert"],
  },
  {
    id: "units-weight",
    name: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, and more",
    href: "/tools/units/weight",
    icon: "Weight",
    category: "units",
    status: "inactive",
    tags: ["units", "weight", "convert"],
  },
  {
    id: "units-temperature",
    name: "Temperature",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    href: "/tools/units/temperature",
    icon: "Thermometer",
    category: "units",
    status: "inactive",
    tags: ["units", "temperature", "convert"],
  },
  {
    id: "units-area",
    name: "Area Converter",
    description: "Convert between square meters, acres, hectares",
    href: "/tools/units/area",
    icon: "Square",
    category: "units",
    status: "inactive",
    tags: ["units", "area", "convert"],
  },
  {
    id: "units-volume",
    name: "Volume Converter",
    description: "Convert between liters, gallons, cups, and more",
    href: "/tools/units/volume",
    icon: "Beaker",
    category: "units",
    status: "inactive",
    tags: ["units", "volume", "convert"],
  },
  {
    id: "units-data",
    name: "Data Storage",
    description: "Convert between bytes, KB, MB, GB, TB",
    href: "/tools/units/data",
    icon: "HardDrive",
    category: "units",
    status: "inactive",
    tags: ["units", "data", "storage"],
  },
  {
    id: "units-angle",
    name: "Angle Converter",
    description: "Convert between degrees, radians, gradians",
    href: "/tools/units/angle",
    icon: "RotateCcw",
    category: "units",
    status: "inactive",
    tags: ["units", "angle", "convert"],
  },
  {
    id: "units-pressure",
    name: "Pressure Converter",
    description: "Convert between PSI, bar, pascal, and more",
    href: "/tools/units/pressure",
    icon: "Gauge",
    category: "units",
    status: "inactive",
    tags: ["units", "pressure", "convert"],
  },
  {
    id: "units-energy",
    name: "Energy Converter",
    description: "Convert between joules, calories, BTU",
    href: "/tools/units/energy",
    icon: "Zap",
    category: "units",
    status: "inactive",
    tags: ["units", "energy", "convert"],
  },
  {
    id: "units-power",
    name: "Power Converter",
    description: "Convert between watts, horsepower, BTU/hr",
    href: "/tools/units/power",
    icon: "Power",
    category: "units",
    status: "inactive",
    tags: ["units", "power", "convert"],
  },
  {
    id: "units-speed",
    name: "Speed Converter",
    description: "Convert between mph, km/h, m/s, knots",
    href: "/tools/units/speed",
    icon: "FastForwardIcon",
    category: "units",
    status: "inactive",
    tags: ["units", "speed", "convert"],
  },
  {
    id: "units-frequency",
    name: "Frequency",
    description: "Convert between Hz, kHz, MHz, GHz",
    href: "/tools/units/frequency",
    icon: "Radio",
    category: "units",
    status: "inactive",
    tags: ["units", "frequency", "convert"],
  },
  {
    id: "units-fuel",
    name: "Fuel Efficiency",
    description: "Convert between MPG, L/100km, km/L",
    href: "/tools/units/fuel",
    icon: "Fuel",
    category: "units",
    status: "inactive",
    tags: ["units", "fuel", "efficiency"],
  },
  {
    id: "units-currency",
    name: "Currency (Offline)",
    description: "Basic currency conversion without live rates",
    href: "/tools/units/currency",
    icon: "DollarSign",
    category: "units",
    status: "inactive",
    tags: ["units", "currency", "convert"],
  },
  {
    id: "units-time",
    name: "Time Converter",
    description: "Convert between seconds, minutes, hours, days",
    href: "/tools/units/time",
    icon: "Clock",
    category: "units",
    status: "inactive",
    tags: ["units", "time", "convert"],
  },

  // General Utilities (20 tools)
  {
    id: "general-password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with custom options",
    href: "/tools/general/password-generator",
    icon: "Key",
    category: "general",
    status: "active",
    tags: ["password", "generate", "security"],
    featured: true,
    popular: true,
  },
  {
    id: "general-qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and data",
    href: "/tools/general/qr-generator",
    icon: "QrCode",
    category: "general",
    status: "active",
    tags: ["qr", "code", "generate"],
  },
  {
    id: "general-password-checker",
    name: "Password Checker",
    description: "Check password strength and security",
    href: "/tools/general/password-checker",
    icon: "Shield",
    category: "general",
    status: "inactive",
    tags: ["password", "check", "security"],
  },
  {
    id: "general-barcode",
    name: "Barcode Generator",
    description: "Generate various types of barcodes",
    href: "/tools/general/barcode",
    icon: "Barcode",
    category: "general",
    status: "inactive",
    tags: ["barcode", "generate", "code"],
  },
  {
    id: "general-color-picker",
    name: "Color Picker",
    description: "Pick and convert colors between formats",
    href: "/tools/general/color-picker",
    icon: "Palette",
    category: "general",
    status: "inactive",
    tags: ["color", "picker", "convert"],
  },
  {
    id: "general-file-hash",
    name: "File Hash",
    description: "Generate MD5, SHA1, SHA256 hashes for files",
    href: "/tools/general/file-hash",
    icon: "Hash",
    category: "general",
    status: "inactive",
    tags: ["file", "hash", "checksum"],
  },
  {
    id: "general-random-color",
    name: "Random Color",
    description: "Generate random colors and palettes",
    href: "/tools/general/random-color",
    icon: "Shuffle",
    category: "general",
    status: "inactive",
    tags: ["color", "random", "palette"],
  },
  {
    id: "general-file-compressor",
    name: "File Compressor",
    description: "Compress files and create archives",
    href: "/tools/general/file-compressor",
    icon: "Archive",
    category: "general",
    status: "inactive",
    tags: ["file", "compress", "archive"],
  },
  {
    id: "general-csv-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON format",
    href: "/tools/general/csv-json",
    icon: "ImageIcon",
    category: "general",
    status: "inactive",
    tags: ["csv", "json", "convert"],
  },
  {
    id: "general-image-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 data URLs",
    href: "/tools/general/image-base64",
    icon: "ImageIcon",
    category: "general",
    status: "inactive",
    tags: ["image", "base64", "convert"],
  },
  {
    id: "general-storage",
    name: "Storage Explorer",
    description: "Explore browser storage (localStorage, sessionStorage)",
    href: "/tools/general/storage",
    icon: "Database",
    category: "general",
    status: "inactive",
    tags: ["storage", "browser", "explore"],
  },
  {
    id: "general-unit-test",
    name: "Unit Test Generator",
    description: "Generate unit test templates",
    href: "/tools/general/unit-test",
    icon: "TestTube",
    category: "general",
    status: "inactive",
    tags: ["test", "unit", "generate"],
  },
  {
    id: "general-ascii-art",
    name: "ASCII Art",
    description: "Convert text to ASCII art",
    href: "/tools/general/ascii-art",
    icon: "Type",
    category: "general",
    status: "inactive",
    tags: ["ascii", "art", "text"],
  },
  {
    id: "general-gradient",
    name: "Gradient Generator",
    description: "Create CSS gradients visually",
    href: "/tools/general/gradient",
    icon: "Paintbrush",
    category: "general",
    status: "inactive",
    tags: ["gradient", "css", "generate"],
  },
  {
    id: "general-compatibility",
    name: "Browser Compatibility",
    description: "Check browser feature compatibility",
    href: "/tools/general/compatibility",
    icon: "Globe",
    category: "general",
    status: "inactive",
    tags: ["browser", "compatibility", "check"],
  },
  {
    id: "general-counter",
    name: "Counter Tool",
    description: "Simple click counter with history",
    href: "/tools/general/counter",
    icon: "Plus",
    category: "general",
    status: "inactive",
    tags: ["counter", "click", "count"],
  },
  {
    id: "general-text-merger",
    name: "Text Merger",
    description: "Merge multiple text files or inputs",
    href: "/tools/general/text-merger",
    icon: "Merge",
    category: "general",
    status: "inactive",
    tags: ["text", "merge", "combine"],
  },
  {
    id: "general-search-query",
    name: "Google Search Query",
    description: "Build advanced Google search queries",
    href: "/tools/general/search-query",
    icon: "Search",
    category: "general",
    status: "inactive",
    tags: ["search", "google", "query"],
  },
  {
    id: "general-speech-to-text",
    name: "Speech to Text",
    description: "Convert speech to text using browser API",
    href: "/tools/general/speech-to-text",
    icon: "Mic",
    category: "general",
    status: "inactive",
    tags: ["speech", "text", "convert"],
  },
  {
    id: "general-text-to-speech",
    name: "Text to Speech",
    description: "Convert text to speech audio",
    href: "/tools/general/text-to-speech",
    icon: "Volume2",
    category: "general",
    status: "inactive",
    tags: ["text", "speech", "audio"],
  },

  // Web3 & Crypto Tools (5 tools)
  {
    id: "web3-wallet-overview",
    name: "Wallet Portfolio",
    description: "Overview and analytics for SOLANA wallets",
    href: "/tools/web3/wallet-overview",
    icon: "Wallet",
    category: "web3",
    status: "active",
    tags: ["wallet", "portfolio", "crypto", "analytics"],
    featured: true,
    popular: true,
  },
  {
    id: "web3-vanity-generator",
    name: "Vanity Address Generator",
    description: "Generate custom SOLANA addresses",
    href: "/tools/web3/vanity-generator",
    icon: "Hash",
    category: "web3",
    status: "active",
    tags: ["vanity", "address", "crypto", "generate"],
    popular: true,
  },
  {
    id: "web3-wallet-generator",
    name: "Wallet Generator",
    description: "Generate new SOLANA wallets",
    href: "/tools/web3/wallet-generator",
    icon: "Key",
    category: "web3",
    status: "active",
    tags: ["wallet", "generate", "crypto", "key"],
  },
  {
    id: "web3-transaction-decoder",
    name: "Transaction Decoder",
    description: "Decode and analyze SOLANA transactions",
    href: "/tools/web3/transaction-decoder",
    icon: "Search",
    category: "web3",
    status: "active",
    tags: ["transaction", "decode", "blockchain"],
  },
  {
    id: "web3-address-validator",
    name: "Address Validator",
    description: "Validate SOLANA addresses",
    href: "/tools/web3/address-validator",
    icon: "CheckCircle",
    category: "web3",
    status: "active",
    tags: ["address", "validate", "crypto"],
  },
];

/**
 * Gets all tools in a specific category
 * @param categoryId - Category identifier
 * @returns Array of tools in the category
 */
export const getToolsByCategory = (categoryId: string): Tool[] => {
  return allTools.filter((tool) => tool.category === categoryId);
};

/**
 * Gets active tools in a specific category
 * @param categoryId - Category identifier
 * @returns Array of active tools in the category
 */
export const getActiveToolsByCategory = (categoryId: string): Tool[] => {
  return allTools.filter(
    (tool) => tool.category === categoryId && tool.status === "active",
  );
};

/**
 * Gets all featured tools
 * @returns Array of featured active tools
 */
export const getFeaturedTools = (): Tool[] => {
  return allTools.filter((tool) => tool.featured && tool.status === "active");
};

/**
 * Gets all popular tools
 * @returns Array of popular active tools
 */
export const getPopularTools = (): Tool[] => {
  return allTools.filter((tool) => tool.popular && tool.status === "active");
};

/**
 * Gets all active tools
 * @returns Array of all active tools
 */
export const getAllActiveTools = (): Tool[] => {
  return allTools.filter((tool) => tool.status === "active");
};

/**
 * Gets tool by ID
 * @param id - Tool identifier
 * @returns Tool object or undefined
 */
export const getToolById = (id: string): Tool | undefined => {
  return allTools.find((tool) => tool.id === id);
};

/**
 * Gets category by ID
 * @param id - Category identifier
 * @returns Category object or undefined
 */
export const getCategoryById = (id: string): ToolCategory | undefined => {
  return toolCategories.find((category) => category.id === id);
};

/**
 * Searches tools by query string
 * @param query - Search query
 * @returns Array of matching active tools
 */
export const searchTools = (query: string): Tool[] => {
  const lowercaseQuery = query.toLowerCase();
  return allTools.filter(
    (tool) =>
      tool.status === "active" &&
      (tool.name.toLowerCase().includes(lowercaseQuery) ||
        tool.description.toLowerCase().includes(lowercaseQuery) ||
        tool.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery))),
  );
};

/**
 * Gets comprehensive tool statistics
 * @returns Object with tool counts and category statistics
 */
export const getToolStats = () => {
  const totalTools = allTools.length;
  const activeTools = getAllActiveTools().length;
  const inactiveTools = allTools.filter(
    (tool) => tool.status === "inactive",
  ).length;
  const betaTools = allTools.filter((tool) => tool.status === "beta").length;

  const categoryStats = toolCategories.map((category) => ({
    ...category,
    totalTools: getToolsByCategory(category.id).length,
    activeTools: getActiveToolsByCategory(category.id).length,
  }));

  return {
    totalTools,
    activeTools,
    inactiveTools,
    betaTools,
    categoryStats,
  };
};
